version: "3.7"

networks:
  elknw:
    
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    networks:
      - elknw
    environment:
      - discovery.type=single-node
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elknw
    depends_on:
      - elasticsearch
